title = "Satbhav Voleti"
theme = "hugo-theme-flat"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 6
baseURL = "https://satbhavvoleti.github.io"

[author]
name = "Satbhav Voleti"

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


# you can set multi row of footers like these
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Contact Me"
url = "https://satbhavvoleti.github.io"
pre = "Email me at satbhav.voleti@gmail.com "

# [[params.footer_rows]]
# [[params.footer_rows.items]]
# name = "Hugo"
# url = "https://gohugo.io"
# pre = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
# [[params.footer_rows.items]]
# name = "theme flat"
# url = "https://cgit.leafee98.com/hugo-theme-flat.git"
# pre = "Theme <a href=\"https://git.leafee98.com/leafee98/hugo-theme-flat.git\">hugo-theme-flat</a>"


[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

[[menus.main]]
name = "Writings"
url = "/writings/"
weight = 40

[[menus.main]]
pageref = "about"
name = "About"
weight = 80

[[menus.main]]
name = "Useful Links"
pageref = "useful links"
weight = 60

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'


# 2-level sub menus are supported
# [[menus.main]]
# name = "Services"
# weight = 60
# [[menus.main]]
# parent = "Services"
# name = "Service A"
# url = "#"
# [[menus.main]]
# parent = "Services"
# name = "Service B"
# url = "#"
